MYSQL_HOST: himcs.io
server:
  port: 8811
spring:
  application:
    name: business-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/seata-business?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    password: root
    username: root
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group # 事务分组